# Schema for the configuration files of the CKEditor module.
field.field_settings.sections:
  type: mapping
  label: 'Sections settings'
  mapping:
    template:
      type: string
      label: 'Main Template'
    filter_format:
      type: string
      label: 'JSON filter format'

field.widget.settings.sections_editor:
  type: mapping
  label: 'Sections editor (multiple rows) display format settings'
  mapping:
    rows:
      type: integer
      label: 'Rows'
    placeholder:
      type: label
      label: 'Placeholder'

editor.settings.ckeditor5_sections:
  type: mapping
  label: 'CKEditor5 Sections settings'
  mapping:
    editorBuild:
      type: string
      label: 'Root element'
    advanced:
      type: string
      label: 'Advanced settings'
    plugins:
      type: mapping
      label: 'Plugins'
      mapping:
        drupallink:
          type: mapping
          label: 'Drupal link configuration'
          mapping:
            linkit_enabled:
              type: integer
            linkit_profile:
              type: string
